GetResult integration.
peaksoft-school/health-check-js10 pull request #34
Opened 2023-12-14 10:49 UTC by karachachit

2023-12-14 11:58 UTC, bekishh commented on src/components/GetResult.jsx
> +                           style={{ background: '#F91515' }}
inline style

2023-12-14 11:58 UTC, bekishh commented on src/components/GetResult.jsx
> +                           }}
iniline style

2023-12-14 11:58 UTC, bekishh commented on src/components/GetResult.jsx
> +                  <li style={{ color: 'red' }}>
inline style

2023-12-14 11:58 UTC, bekishh commented on src/components/GetResult.jsx
> +            // eslint-disable-next-line new-cap
eslint not disable

2023-12-15 04:23 UTC, AziatAbd requested changes

2023-12-15 04:23 UTC, AziatAbd commented on src/App.js
> +         <GetResult />
<AppRoutes /> Кайтарып койун

2023-12-15 04:23 UTC, AziatAbd commented on src/config/axiosInstance.js
> +   const token =
токен стордон алын

2023-12-15 04:25 UTC, AziatAbd commented
роуты тоже подготовьте

2023-12-26 08:15 UTC, merged